//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int Id { get; set; }
        public string Rate { get; set; }
        public string Comment { get; set; }
        public System.DateTime Time { get; set; }
        public int OrderId { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
